# .github/workflows/render-md-mermaid.yml

name: render-md-mermaid

on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render images for Mermaid diagrams
        run: |
          chmod +x scripts/render-md-mermaid.sh
          make render-md-mermaid

      - name: Commit rendered png and svg files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "*.svg *.png"
          commit_message: "docs: automatically rendered mermaid diagrams"
